### ISSUE TITLE
Running In Priority-Only Returns Error

### ISSUE THREAD

**Issue by Sevenyx** [xKynn/PokecordCatcher#16]
`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 223, in _run_event
  File "I:\PokecordCatcher\pokecordcatcher.py", line 39, in on_message
TypeError: 'str' object cannot be interpreted as an integer`

It also fails to catch the pokemon.

**Comment by xKynn** [comment]
can you post your config without the token in it?

**Comment by Sevenyx** [comment]
This was in the previous version. I didn't realize there was an update, so I upgraded to the 0.2.5 release just now, and it works perfectly.
