### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by Antzelino** [xKynn/PokecordCatcher#53]
I see that we have to launch a .exe file, can we make this run in linux as well?

**Comment by Antzelino** [comment]
for some reason its not working for me:

Traceback (most recent call last): 
  File "launcher.py", line 2, in <module> 
    from pokecordcatcher import Poke 
  File "/home/one/Downloads/PokecordCatcher-1.0.2/pokecordcatcher.py", line 91 
    await message.channel.send(f"{pref} {name}") 
                                              ^ 
SyntaxError: invalid syntax

when i do `python launcher.py`

**Comment by xKynn** [comment]
your python version should be 3.6+
