### ISSUE TITLE
Help Running on Mac

### ISSUE THREAD

**Issue by pazzaro** [xKynn/PokecordCatcher#64]
need assistance please im on a mac and im not sure how to use the requirements but i downloaded it already i also pasted my token already everytime i launch launcher.py with terminal it shows this message:

Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokecordcatcher import Poke
  File "/Users/Nate/Downloads/PokecordCatcher-master/pokecordcatcher.py", line 14
    def __init__(self, config_path: str, *args, **kwargs):
                                  ^
SyntaxError: invalid syntax

please help me ;_;

**Comment by bueluke** [comment]
ummm

**Comment by Hyperclaw79** [comment]
Update your python verison and refer to some of the closed issues on this repo.
Also, refer to your [own issue](https://github.com/Hyperclaw79/PokeBall-SelfBot/issues/55) on my bot.
