### ISSUE TITLE
Getting error trying to run

### ISSUE THREAD

**Issue by Auroric** [xKynn/PokecordCatcher#72]
`Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 710, in _create_direct_connection
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 777, in create_connection
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 764, in create_connection
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 451, in sock_connect
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 481, in _sock_connect_cb
TimeoutError: [Errno 10060] Connect call failed ('192.30.255.116', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 378, in connect
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 687, in _create_connection
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 737, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: [Errno 10060] Can not connect to api.github.com:80 [Connect call failed ('192.30.255.116', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 223, in _run_event
  File "I:\PokecordCatcher\pokecordcatcher.py", line 113, in on_ready
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\client.py", line 603, in __aenter__
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\client.py", line 231, in _request
  File "C:\Users\lenovo pc\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 383, in connect
aiohttp.client_exceptions.ClientConnectorError: [Errno 10060] Cannot connect to host api.github.com:80 ssl:False [Can not connect to api.github.com:80 [Connect call failed ('192.30.255.116', 80)]]`

**Comment by Auroric** [comment]
`Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 778, in create_connection
    raise exceptions[0]
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\asyncio\selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 10060] Connect call failed ('192.30.255.117', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 10060] Can not connect to api.github.com:80 [Connect call failed ('192.30.255.117', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "C:\Users\aaron\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 660, in on_ready
    async with sess.get("http://api.github.com/repos/Hyperclaw79/PokeBall-SelfBot/contents/_version.json") as resp:
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 10060] Cannot connect to host api.github.com:80 ssl:False [Can not connect to api.github.com:80 [Connect call failed ('192.30.255.117', 80)]]`

Also getting this as an error trying to run

**Comment by Auroric** [comment]
Have attempted to pip update aiohttp, error remains the same.

**Comment by bueluke** [comment]
not a pip problem. problem with your wifi 😂 is the computer you're running the bot on connected to wifi?

**Comment by bueluke** [comment]
Problem fixed in discord (aiohttp  update)

**Comment by Auroric** [comment]
FYI I got it to work by turning off the update checker. Have not tested with aiohttp update and checker on yet.
